name: Clippy integration tests
on: [push]
jobs:
  parallel-runs-across-platforms:
    name: Run integration tests on every OS
    strategy:
      matrix:
        # run 2 copies of the current job in parallel
        # and they will load balance all specs
        os: ["ubuntu-latest", "macos-latest"]
        containers: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # because of "record" and "parallel" parameters
      # these containers will load balance all found tests among themselves
      - name: run tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          wait-on: http://localhost:3000/clippy
          group: Parallel 2x on ${{ matrix.os }}
          # on Mac and Linux we can use "npm start"
          start: npm start
