name: Clippy integration tests
on: [push]
jobs:
  parallel-runs-across-platforms:
    name: Run integration tests on every OS
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: cypress-io/github-action@v2
        with:
          wait-on: http://localhost:3000/clippy
          start: npm start
